# Generated by Django 2.1.3 on 2019-04-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='college',
            field=models.CharField(default=1, max_length=20, verbose_name='学院'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='borrowNum',
            field=models.IntegerField(default=0, verbose_name='在借册数'),
        ),
    ]
