# Generated by Django 2.1.3 on 2019-04-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20190410_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default=1, max_length=15, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
