# Generated by Django 2.1.3 on 2019-04-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15, verbose_name='管理员账号')),
                ('password', models.CharField(max_length=15, verbose_name='管理员密码')),
            ],
        ),
        migrations.RemoveField(
            model_name='borrowform',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowform',
            name='student',
        ),
        migrations.RemoveField(
            model_name='returnform',
            name='book',
        ),
        migrations.RemoveField(
            model_name='returnform',
            name='student',
        ),
        migrations.DeleteModel(
            name='borrowForm',
        ),
        migrations.DeleteModel(
            name='returnForm',
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
