# Generated by Django 2.1.3 on 2019-04-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_auto_20190402_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='booktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=15, verbose_name='书籍类型')),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.booktype', verbose_name='类型'),
        ),
    ]
