# Generated by Django 2.1.3 on 2019-04-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_auto_20190404_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='manager',
            field=models.CharField(default=1, max_length=20, verbose_name='管理员名字'),
            preserve_default=False,
        ),
    ]
