# Generated by Django 2.1.3 on 2019-04-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_managers_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
        ),
    ]
