# Generated by Django 2.1.3 on 2019-04-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_auto_20190407_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='place',
            field=models.CharField(max_length=80, verbose_name='存放位置'),
        ),
    ]
