# Generated by Django 2.1.3 on 2019-04-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_auto_20190413_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
    ]
