# Generated by Django 2.1.3 on 2019-04-02 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
        ('Manager', '0002_auto_20190402_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowTime', models.DateTimeField(auto_now_add=True, verbose_name='借书时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.books', verbose_name='图书')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.students', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='returnForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowTime', models.DateTimeField(auto_now_add=True, verbose_name='借书时间')),
                ('returnTime', models.DateTimeField(auto_now_add=True, verbose_name='还书时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.books', verbose_name='图书')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.students', verbose_name='学生')),
            ],
        ),
    ]
