# Generated by Django 2.1.3 on 2019-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnform',
            name='borrowTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='借书时间'),
        ),
        migrations.AlterField(
            model_name='returnform',
            name='returnTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='还书时间'),
        ),
    ]
