# Generated by Django 2.1.3 on 2019-04-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_remove_returnform_borrowtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnform',
            name='borrowTime',
            field=models.DateTimeField(null=True, verbose_name='借书时间'),
        ),
    ]
